#!/usr/bin/env python3
"""Generate the web map legend from infra/planning/legend_map.csv.

Usage:
    python gen_web_legend.py

Writes apps/web/lib/planning/legend.generated.ts: one entry per native zone label
(legend order; first row wins for a label or a colour), with its colour and class_norm. Map symbols
(NGT hatch, forest glyphs, streams) are overlays and are styled in the web code.
"""

import csv
import json
import os

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SRC = os.path.join(REPO, "infra", "planning", "legend_map.csv")
OUT = os.path.join(REPO, "apps", "web", "lib", "planning", "legend.generated.ts")


def main():
    with open(SRC, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    entries, seen, colours = [], set(), set()
    for r in rows:
        if r["role"] != "zone" or not r["colour_hex"].startswith("#"):
            continue
        label = r["zone_label_native"]
        # streams are a centreline overlay now; a label sharing an earlier row's colour
        # (left-column "Water bodies") never appears in the zone data
        if label in seen or label == "Streams" or r["colour_hex"] in colours:
            continue
        seen.add(label)
        colours.add(r["colour_hex"])
        entries.append(
            {
                "planId": r["plan_id"],
                "label": label,
                "colour": r["colour_hex"],
                "classNorm": r["class_norm"],
            }
        )
    body = json.dumps(entries, indent=2)
    ts = (
        "// Copyright (c) 2026 Qnit. All rights reserved.\n"
        "// SPDX-License-Identifier: LicenseRef-Proprietary\n"
        "//\n"
        "// GENERATED by infra/scripts/planning/gen_web_legend.py from\n"
        "// infra/planning/legend_map.csv. Do not edit by hand.\n\n"
        "export interface LegendEntry {\n"
        "  planId: string;\n"
        "  label: string; // native legend text from the plan sheet\n"
        "  colour: string;\n"
        "  classNorm: string;\n"
        "}\n\n"
        f"export const PLANNING_LEGEND: LegendEntry[] = {body};\n"
    )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(ts)
    print(f"wrote {OUT}: {len(entries)} entries")


if __name__ == "__main__":
    main()
