// Copyright (c) 2026 Qnit. All rights reserved.
// SPDX-License-Identifier: LicenseRef-Proprietary
//
// GENERATED by infra/scripts/planning/gen_web_legend.py from
// infra/planning/legend_map.csv. Do not edit by hand.

export interface LegendEntry {
  planId: string;
  label: string; // native legend text from the plan sheet
  colour: string;
  classNorm: string;
}

export const PLANNING_LEGEND: LegendEntry[] = [
  {
    "planId": "BDA-RMP2031",
    "label": "Residential",
    "colour": "#ffff00",
    "classNorm": "residential"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Commercial",
    "colour": "#005ce6",
    "classNorm": "commercial"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Industrial",
    "colour": "#ca7af5",
    "classNorm": "industrial"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Public and Semi Public",
    "colour": "#ff0000",
    "classNorm": "public_semi_public"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Defense",
    "colour": "#b2b2b2",
    "classNorm": "defence"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Public Utilities",
    "colour": "#732600",
    "classNorm": "public_utility"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Parks and Open spaces",
    "colour": "#267300",
    "classNorm": "open_space"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Transport and Communication",
    "colour": "#686868",
    "classNorm": "transport"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Agriculture",
    "colour": "#a3ff73",
    "classNorm": "agriculture"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Water Bodies",
    "colour": "#97dbf2",
    "classNorm": "water"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Not coloured on the plan",
    "colour": "#ffffff",
    "classNorm": "uncoloured"
  },
  {
    "planId": "BDA-RMP2031",
    "label": "Road space (not coloured on the plan)",
    "colour": "#ffffff",
    "classNorm": "road_space"
  }
];
